# Generated by Django 4.0.6 on 2022-07-26 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='menu.section'),
        ),
        migrations.AlterField(
            model_name='modifiers',
            name='item',
            field=models.ManyToManyField(related_name='item', to='menu.item'),
        ),
    ]
