# Generated by Django 4.0.6 on 2022-07-26 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_item_section_alter_modifiers_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.section'),
        ),
        migrations.AlterField(
            model_name='modifiers',
            name='item',
            field=models.ManyToManyField(related_name='modifiers', to='menu.item'),
        ),
    ]
